// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0NCSKoULyxVBN84E49yPhQZjbaysMvgE',
    appId: '1:734665122236:web:f5d89216018bfb6b748bb9',
    messagingSenderId: '734665122236',
    projectId: 'safe-chat-21e68',
    authDomain: 'safe-chat-21e68.firebaseapp.com',
    storageBucket: 'safe-chat-21e68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAocKKn_QEhNelWL809swElueeIRzSDPI',
    appId: '1:734665122236:android:445be8685252f313748bb9',
    messagingSenderId: '734665122236',
    projectId: 'safe-chat-21e68',
    storageBucket: 'safe-chat-21e68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2_DMLxG_AOniJnUU4NbDLVWrLATx9ZlU',
    appId: '1:734665122236:ios:6c328131351c64a3748bb9',
    messagingSenderId: '734665122236',
    projectId: 'safe-chat-21e68',
    storageBucket: 'safe-chat-21e68.appspot.com',
    iosBundleId: 'com.example.safeChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2_DMLxG_AOniJnUU4NbDLVWrLATx9ZlU',
    appId: '1:734665122236:ios:6c328131351c64a3748bb9',
    messagingSenderId: '734665122236',
    projectId: 'safe-chat-21e68',
    storageBucket: 'safe-chat-21e68.appspot.com',
    iosBundleId: 'com.example.safeChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0NCSKoULyxVBN84E49yPhQZjbaysMvgE',
    appId: '1:734665122236:web:ab2219d75267bc97748bb9',
    messagingSenderId: '734665122236',
    projectId: 'safe-chat-21e68',
    authDomain: 'safe-chat-21e68.firebaseapp.com',
    storageBucket: 'safe-chat-21e68.appspot.com',
  );
}
